- provision-team/provision_aks.sh
- provision-team/setup.sh
- provision-vm/proctorVMSetup.sh
When kubectl is not installed on the proctor VM, the script will fail to install `kubectl` after the AKS even though the setup script was run as `sudo`.  This changes the kubectl dependency to install as a prerequisite.
VM Provision script fixes:
- removes prompts from the `mssql` package install
- sets proper permissions to the cloned directory
> Kubectl fix

- provision-team/README.md
- provision-vm/azuredeploy.json
- provision-vm/azuredeploy.parameters.json
- provision-vm/deploy.ps1
- provision-vm/proctorVMSetup.sh
- provision-vm/readme.md
The proctor VM will not complete as-is due to some issues with the provisioning script.
- Fixed provisioning, verified all tools working upon login
- Updated template to use the latest version of LTS to not have to patch as much, auto update security patches in the script
- Change the connection mechanism to use SSH key instead of a password for the VM
> Fix and update the Proctor VM, documentation

- provision-team/cleanup_environment.sh
- provision-team/configure_sql.sh
- provision-team/provision_sql_mobileapp.sh
- Fix the sql server secrets to not have a new line when they are base64 encoded, causing the api-user database connection to fail
- Make the sql username secret have the `@` sqlserverFQDN at the end 
- Add back in the copy of kube config file for the cleanup script
> Fix kubernetes sql secrets

- provision-team/configure_sql.sh
Workaround to execute sqlcmd: 
Append the full path to **_sqlcmd_** call. 
**FROM:**
sqlcmd -U $sqlServerUsername -P $sqlPassword -S $sqlServerFQDN -d $sqlDBName -i ./MYDrivingDB.sql -e
**TO:**
/opt/mssql-tools/bin/sqlcmd -U $sqlServerUsername -P $sqlPassword -S $sqlServerFQDN -d $sqlDBName -i ./MYDrivingDB.sql -e
> fixed sqlcmd path

- provision-team/README.md
- provision-team/setup.sh
Allows the provision-team setup script to optionally specify a team number else will fall back to provisioning a random number.  This makes life much easier for sentinel to make connections to the team environment and provisioning teams in parallel (to be done).
> Provision-Team allow specified team numbers

- provision-team/deploy_ingress_dns.sh
Despite having all the checks in place, I still just had a tiller timing failure on a complete run:
```
Installing Traefik Ingress controller ...
Waiting for tiller to be ready
Error: could not find a ready tiller pod
```
Tiller was actually already installed with no errors.
This will help to avoid this problem.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
> Improve tiller resliency

- leaderboard/api/Leaderboard/RestAPI.cs
- provision-proctor/build_deploy_web.sh
- provision-proctor/setup.sh
I run through the deployment process. 
I fix several things to prevent automation. 
The proctor-environment deployment script asks me the name of team name during the deployment process. I can't find it. 
Please merge this and try to deploy proctor environment. 
1. Teams Deployments
2. Edit these files to have valid data.
https://github.com/Azure-Samples/openhack-devops-proctor/blob/master/leaderboard/api/CLI/team_service_config.json
and 
https://github.com/Azure-Samples/openhack-devops-proctor/blob/master/leaderboard/web/src/environments/environment.prod.ts
3. deploy Proctor environment setup script
For more detail, please ask David. :)
> Remove the host code for automation

- leaderboard/api/CLI/CLI.csproj
- leaderboard/api/CLI/Program.cs
- leaderboard/api/SharedLibrary/DocumentService.cs
- leaderboard/sentinel/helm/templates/pod.yaml
- leaderboard/web/src/environments/environment.prod.ts
- leaderboard/web/src/environments/environment.ts
I fix two things. 
1. The endpoint URL of the failure report
2.  json file is not copied to the bin folder.
3. fix the issue that db is not match with sentinel 
https://github.com/Azure-Samples/openhack-devops-proctor/issues/65
currently, I investigating the root cause of 
https://github.com/Azure-Samples/openhack-devops-proctor/issues/66
However it is not done yet. Maybe Osvaldo can help. 
The problem is , When I query Service it returns no result (I confirm it has the data).  When I change it into the ReadDocumentAsync, current code returns ` PartitionKey value must be supplied for this operation.` Although we have PratitionKey.  However, times up. ( Now 0 am ...)
https://github.com/Azure-Samples/openhack-devops-proctor/blob/fix/leaderboardurl/leaderboard/api/SharedLibrary/DocumentServic …
> fix: endpoint names 

- leaderboard/web/Dockerfile
- leaderboard/web/src/app/pages/dashboard/dashboard.component.ts
- leaderboard/web/src/app/pages/dashboard/solar/solar.component.ts
Fix `npm run build:prod`
When you do a `npm run build:prod` it errors out with:
ERROR in src\app\pages\dashboard\dashboard.component.html(1,15): : Property 'viewTeams' is private and only accessible
within class 'DashboardComponent'.
src\app\pages\dashboard\solar\solar.component.ts.SolarComponent.html(3,19): : Property 'teamName' is private and only accessible within class 'SolarComponent'.
src\app\pages\dashboard\solar\solar.component.ts.SolarComponent.html(8,26): : Property 'teamPoint' is private and only
accessible within class 'SolarComponent'.
src\app\pages\dashboard\solar\solar.component.ts.SolarComponent.html(9,47): : Property 'teamUptime' is private and only accessible within class 'SolarComponent'.
If you view the current web leaderboard it gives this on the initial startup: …
> Fix leaderboard web build:prod

- provision-team/deploy_ingress_dns.sh
- provision-team/provision_aks.sh
- provision-team/setup.sh
- provision-vm/proctorVMSetup.sh
This adds a verification on the az cli version to 2.0.41 by default since we upgraded the cli version in #94 and add --disable-rbac when provisioning the aks cluster.
@rguthriemsft PTAL
> added verification of az cli version and --disable-rbac on aks cluster

- leaderboard/api/helm/templates/deployment.yaml
- leaderboard/api/web/Auth/IJwtFactory.cs
- leaderboard/api/web/Auth/JwtFactory.cs
- leaderboard/api/web/Controllers/AccountsController.cs
- leaderboard/api/web/Controllers/AuthController.cs
- leaderboard/api/web/Data/AppUserContext.cs
- leaderboard/api/web/Helpers/Constants.cs
- leaderboard/api/web/Helpers/Errors.cs
- leaderboard/api/web/Helpers/ResponseExtensions.cs
- leaderboard/api/web/Helpers/Tokens.cs
- leaderboard/api/web/Models/AppUser.cs
- leaderboard/api/web/Models/JwtIssuerOptions.cs
- leaderboard/api/web/Models/View/CredentialsViewModel.cs
- leaderboard/api/web/Models/View/Mappings/ViewModelToEntityMappingProfile.cs
- leaderboard/api/web/Models/View/RegistrationViewModel.cs
- leaderboard/api/web/Models/View/Validations/CredentialsViewModelValidator.cs
- leaderboard/api/web/Models/View/Validations/RegistrationViewModelValidator.cs
- leaderboard/api/web/Sentinel.csproj
- leaderboard/api/web/Startup.cs
- leaderboard/api/web/Utility/Configuration.cs
- provision-proctor/build_deploy_sentinel_api.sh
- Adds the ability for new users to be added with email and password and have them login and get back a JWT token
**TO DO (DO NOT MERGE YET)**
> Add User email/pass JWT authentication to Sentinel API

- leaderboard/web/mockserver/index.js
- leaderboard/web/src/environments/environment.prod.ts
- fixes the production build of the leaderboard website to go to `/teams` versus `/teamsteams`
- updates the mockserver to use the same port as the development environment config
> Fix leaderboard api url

- provision-proctor/deploy_sentinel.sh
- provision-proctor/monitoringVMSetup.sh
- provision-proctor/setup.sh
- provision-team/cleanup_environment.sh
Added routine to loop through the user credentials and get their kvstore file then deploy sentinel to point at their IP.
Sentinel has been commented in the setup script since the new deployment script does an exit 1 in the case the file is not present.
```
[X] Yes
[ ] No
```
> Update monitoring deployment to automate sentinel

- provision-team/configure_jenkins.sh
Enables the remote Docker API so that the Docker plugin on Jenkins can connect to the local Docker socket.
> Enable remote API for Docker

- leaderboard/api/helm/values.yaml
- leaderboard/sentinel/helm/templates/NOTES.txt
- provision-proctor/deploy_sentinel.sh
- Allows the ability to deploy sentinel without a CSV file when passing any string to the `-y ` script option.  This is useful when all the local `kvstore` information is already correct on the machine where running the script.
- Fixes the deploy_sentinel script missing the argument
- Skips deploying Sentinel for the monitoring environments which may be present in `kvstore ls`
> Sentinel Improvements

- provision-proctor/deploy_ingress_dns.sh
- provision-team/deploy_ingress_dns.sh
- provision-team/provision_aks.sh
- provision-vm/proctorVMSetup.sh
Bump minor versions for the packages for the following reasons:
- kubernetes cli and AKS [1.11.2 --> 1.11.3](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#changelog-since-v1112)
This is most important: `the API server and client-go libraries have been fixed to support additional non-alpha-numeric characters in UserInfo "extra" data keys. Both should be updated in order to properly support extra data containing "/" characters or other characters disallowed in HTTP headers. `
> Note 1.11.4 available upstream, but not on AKS yet.
- Helm 2.10.0 --> 2.11.0
The tiller does a check using the kubectl client via [this go file](https://github.com/helm/helm/blob/master/pkg/kube/client.go).
There are quite a few package updates with this client included in Helm 2.11.0 which …
> Bump k8s 1.11.3, helm 2.11.0, better helm install

- provision-team/deploy_ingress_dns.sh
Tiller was able to be in a state where you see "Running" but the pod is not actually ready.  This makes the following regex improvements:
* it any number of characters after `kube-system` versus specifically check for 3 whitespace characters
* it checks for `1/1` after tiller to ensure the pod is ready and running
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
> Fix tiller regex ready

- provision-team/README.md
- provision-vm/proctorVMSetup.sh
I'm running some experiments for the DevOps OpenHack and while setting it up on my internal subscription, I've been through some issues to provision the team environment from the proctorVM.
Those changes are based on this experience I had and they helped me have the team environment provisioned.
Improve the experience on provisioning the environment on an internal subscription by using the *nologin* branch.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[X] Feature
```
```
git clone https://github.com/ricardoserradas/openhack-devops-proctor.git
cd openhack-devops-proctor
git …
```
> Fix proctorVM minor issues for nologin branch

- leaderboard/web/package-lock.json
- leaderboard/web/package.json
Fixes CVE-2018-14732 Low severity.  I tested locally a `build`, `build:prod`, and `ng serve` opening up the site and saw no errors / site functioning as planned.  The 0.8.x version of the package snaps to the LTS 6.x branch of angular which the project is already using.
> fix webpack-dev-server vuln

- provision-team/traefik-values.yaml
Makes the Traefik memory limit be 200Mi to help fix issues seen when Traefik has only 100Mi limit.
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Bump Traefik memory to 200Mi

- provision-team/cleanup_environment.sh
- provision-team/run_nginx.sh
- provision-vm/Docker/Dockerfile
- provision-vm/Docker/Readme.md
- provision-vm/Docker/startup.sh
- provision-vm/azuredeploy.json
- provision-vm/proctorVMSetup.sh
We had an issue for deployment of the proctor vm. It is caused by library download. Talking with Damien, we is going to make it to the container. Then it might be no problem for the downloading the library. Also it might be handy for the people. 
I open this PR to talk about the design. 
This is just the first version for enabling container work on docker. 
I wrote a README on the proctor-vm/Docker/Readme for testing Docker solution. 
When I execute the script of team environment, it works. 
* Create a startup script and Dockerfile
* Change some scripts to make it work on container (remove sudo)
* Refactor the script to make it production grade
* Change the proctorVMSetup.sh for installing only docker
* Upload the docker image to the DockerHub and automate the process. 
* Use Volume to …
> Enabling docker for proctor vm deployment

- resources/polling.sh
Healthcheck URl doesn't work for `-I` which means 
```
-I, --head
(HTTP FTP FILE) Fetch the headers only! HTTP-servers feature the command HEAD which this uses to get nothing but the header of a document. When used on an FTP or FILE file, curl displays the file size and last modification time only.
```
it is fix the current issue to change it '-i'. However I'm wondering why it doesn't work for the health check. (I'd like to know why it happens for the learning)
> fix: returns 404 even if it is 200

- tools/get-teams.sh
Update the permissions on kubeconfig so that get-teams can download it.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
> Fixed permissions on kubeconfig

- provision-vm/azuredeploy.json
- provision-vm/proctorVMSetup.sh
Hi,  I fix the problem of these.  However, I can reproduce `sent invalidate....` ones. For the `debconf` one related DEBIAN_FRONTEND=noninteractive.  I add this environment variables for all apt related commands.  for the `sent invalidate...`  You can refer this issue. 
https://www.digitalocean.com/community/questions/debian-9-3-droplet-issues-with-useradd
I simply add `apt-get remove unsc`. Maybe it is help to remove the issue. Could you review it and try actual environment to reproduce the issue. 
```
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell …
```
> Fix: error of deploying proctorVM

- provision-team/jenkins/install_jenkins.sh
- provision-team/provision_aks.sh
- provision-vm/Docker/Dockerfile
* Update provision_aks.sh
Update AKS cluster version from 1.13.11 to 1.15.7
* Update install_jenkins.sh
Update jenkins for 1.15.7 kubectl
* Update Dockerfile
Update proctor container for 1.15.7 kubectl
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update provision_aks.sh (#320)
