provision-team/setup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> uncommented aks acr permissons

provision-team/cleanup_environment.sh, provision-team/setup.sh
=> fixed bug in duplicate team envs due to -_ incorrect names.

.gitignore, provision-team/setup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Revert back to mydrivingdb in setup script

provision-vm/proctorVMSetup.sh
Added installation of MSSQL tools to proctor VM setup (Ubuntu 16.04).
=> Adding mssql tools to proctor VM setup

provision-vm/proctorVMSetup.sh, provision-vm/readme.md
* Adds Powershell Core to provisioning VM to be able to provision the proctor environment PowerShell script.
=> Add PowerShell Core steps to Provision VM

provision-team/MYDrivingDB.sql, provision-team/configure_sql.sh
added schema script. configure temporary firewall rule for allowing proctor vm to run create schema
=> Added script to create database schema as part of configure sql

provision-team/configure_sql.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> echo sql schema output

provision-team/configure_sql.sh, provision-team/setup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> add dbname parameter to configure sql

provision-vm/proctorVMSetup.sh
Add psgallery as trusted repo for unattended install
=> Add psgallaery as trusted repo for unattended install

provision-team/build_deploy_poi.sh, provision-team/build_deploy_trip.sh, provision-team/build_deploy_user.sh, provision-team/setup.sh, provision-vm/proctorVMSetup.sh
Fixes the build poi script to correspond to changes made to the folder structure for the API https://github.com/Azure-Samples/openhack-devops-team/pull/9
=> provision team script fixes

provision-team/build_deploy_poi.sh, provision-team/setup.sh
- fix the poi helm chart value passed for the image repository
- echo the actual command executed for configure sql in setup
=> Fix for poi helm chart

provision-team/build_deploy_poi.sh, provision-team/build_deploy_user.sh, provision-team/cleanup_environment.sh
- Allows the ingress hostname to be passed in as a value versus creating new values.yaml files.
Corresponds with https://github.com/Azure-Samples/openhack-devops-team/pull/17
=> helm install with ingress hostname

provision-team/README.md, provision-vm/proctorVMSetup.sh
run proctor vm setup and clean team install from proctor vm.  -- success
=> Fix ownership on git clone

provision-team/build_deploy_trip.sh, provision-team/build_deploy_user.sh, provision-team/configure_sql.sh, provision-team/deploy_ingress_dns.sh, provision-team/provision_aks_acr_auth.sh, provision-team/service_check.sh, provision-team/setup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fixing usage typos and adding service check

provision-team/setup.sh, provision-vm/proctorVMSetup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix permissions and az login

provision-team/service_check.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix service health check script

provision-team/setup.sh, provision-vm/proctorVMSetup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix path issue

provision-team/setup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix endpoint set

provision-team/build_deploy_simulator.sh
- Creates and deploys simulator to new simulator namespace
- Fixes problem with duplicate image tags being used
=> Simulator helm chart updates

provision-proctor/setup.sh
Adds the kvstore configuration in the same style as already in the provision-team setup.sh.
=> add kvstore config for proctor provision

provision-proctor/setup.sh
Run provisioning script in detached mode
* ...
```
[ ] Yes
[ X] No
```
```
[ X] Bugfix
[ ] Feature
```
=> Added nohup to run script in detached mode

leaderboard/api/CLI/Program.cs, leaderboard/api/Leaderboard/RestAPI.cs, leaderboard/api/SharedLibrary.Test/TeamTest.cs, leaderboard/api/SharedLibrary/DocumentService.cs, leaderboard/api/SharedLibrary/Models.cs
This pull request fix the issue 
https://github.com/Azure-Samples/openhack-devops-proctor/issues/66
I fix the error. 
Why it happens is, When we have a collection with Partition, The CosmosDB SDK Client
linq query ignore the JsonProperty.  That is why query becomes zero results.
https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/31355917-linq-provider-should-respect-jsonserializersetting
Also, I found a bug to forget to update the Service collection.  Now it works. :)
Currently it's ok. However, we can switch Collection into No-Partition DB in the near feature.
=> Backend Error fix

provision-team/build_deploy_poi.sh
=> adding test for poi

provision-team/README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update provision team README

FAQ.md, README.md, leaderboard/README.md
- Add initial root readme
- Update leaderboard readme
- Add new FAQ section
- Add new FAQ for tiller timeout issue and common resolution
=> Add and Update Docs

provision-vm/azuredeploy.json
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fixing vm sku version

provision-team/README.md, provision-vm/readme.md
* Add more information and detailed steps about `nohup`
* Add more information on proctor vm setup and connectivity
=> add nohup docs, more proctor vm ino

provision-proctor/Readme.md
I update the Readme according to the issue of the Ozvaldo's 
https://github.com/Azure-Samples/openhack-devops-proctor/issues/83
=> Update Readme.md for proctor environment

provision-vm/azuredeploy.json, provision-vm/deploy.ps1, provision-vm/readme.md
=> add vm connect output

provision-team/setup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Json default

provision-team/build_launch_json.sh, provision-team/cleanup_environment.sh, provision-team/configure_sql.sh, provision-team/setup.sh, provision-team/templates/launch.json.template, provision-team/templates/tasks.json.template
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Launch json support for team setup.

provision-proctor/setup.sh
=> change proctor resourcegroup name for consistency with team

provision-vm/proctorVMSetup.sh
=> Update az cli to v2.0.38-1

provision-team/deploy_ingress_dns.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Added delay of 45sec to ensure traefik is ready

provision-team/deploy_ingress_dns.sh, provision-team/setup.sh
Fixing tiller service account role assignment.
=> Test k8s fix

provision-proctor/build_deploy_web.sh, provision-proctor/setup.sh
Have leaderboard deployment to use the variables from main script.
=> leaderboard deployment to use values from the main deployment script

provision-team/deploy_ingress_dns.sh, provision-team/provision_aks.sh, provision-team/setup.sh, provision-vm/proctorVMSetup.sh
Pr to your branch before merge to master
=> Add az version check rg

provision-team/traefik/templates/dashboard-ingress.yaml
* Fixes the dashboard to work with the proctor environment
=> fix traefik dashboard paths

provision-proctor/CreateLeaderboardDb.sql
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix db creation script

leaderboard/web/package-lock.json, leaderboard/web/src/app/pages/dashboard/dashboard.component.ts
Not tested yet. 
Please give me the user/password, then I'll test this logic.
=> Update convert logic for new API responses

leaderboard/README.md, leaderboard/api/tests/IntegrationTests/SentinelWebApplicationFactory.cs, leaderboard/sentinel/main.go, provision-proctor/CreateLeaderboardDb.sql
schema and routes to complete leaderboard
=> initial design for completing leaderboard

provision-vm/azuredeploy.json, provision-vm/azuredeploy.parameters.json, provision-vm/deploy.ps1, provision-vm/deploy.sh, provision-vm/proctorVMSetup.sh
- Adds a new bash script to provision the VM
- Auto generate storage account name
- Update Azure RM API versions for template
- Updates VM dependencies
- kubectl 1.10.5
- az to 2.0.43
=> Update Proctor VM

provision-team/build_deploy_user-profile.sh, provision-team/setup.sh
Purpose
1. Add build script for user-profile Java API
2. Modify the setup script to include new build script
=> Add user-java API build deploy script

leaderboard/api/web/Controllers/LeaderboardController.cs, leaderboard/api/web/Data/LeaderboardContext.cs, leaderboard/api/web/Models/Challenge.cs, leaderboard/api/web/Models/ChallengeDefinition.cs, leaderboard/api/web/Models/LogMessage.cs, leaderboard/api/web/Models/Team.cs, leaderboard/api/web/Sentinel.csproj, provision-proctor/CreateLeaderboardDb.sql, provision-proctor/InitLeaderboard.sql, provision-proctor/TestData.sql
=> Leaderboard apis

leaderboard/README.md, leaderboard/api/helm/values.yaml, provision-proctor/CreateLeaderboardDb.sql
- Adds the required tables for the authentication additions to the API
- Updates Readme to include those routes
=> Add SQL tables for auth

leaderboard/api/tests/IntegrationTests/IntegrationTests.csproj, leaderboard/api/web/Controllers/LeaderboardController.cs, leaderboard/api/web/Sentinel.csproj, provision-vm/proctorVMSetup.sh
- Updates all packages to the latest versions
- Fixes problems with build
=> Update Sentinel NuGet packages

provision-team/setup.sh
Purpose
- Update image tag of user-profile
=> Update user-profile tag

provision-team/README.md
Corrections about script execution, purpose of nohup and background usage.
=> nohup readme updates

leaderboard/api/web/Controllers/LeaderboardController.cs, leaderboard/api/web/Models/Challenge.cs, leaderboard/api/web/Startup.cs, leaderboard/proxy.conf.json, leaderboard/web/src/app/app-routing.module.ts, leaderboard/web/src/app/pages/dashboard/dashboard.component.ts, provision-proctor/CreateLeaderboardDb.sql
=> Leaderboard api fix

provision-team/deploy_jenkins.sh
Update the script location that configures Jenkins from my repo to OpenHack repo
=> Update script location to OpenHack repo

provision-vm/azuredeploy.json
The URL was pointing to a deleted branch
Move provisioning script to use master branch
```
[ X] Yes
[ ] No
```
=> Update URI of provisioning script

leaderboard/web/src/app/pages/pages-menu.ts, leaderboard/web/src/app/pages/pages-routing.module.ts, leaderboard/web/src/app/pages/pages.module.ts, leaderboard/web/src/app/pages/teams/teams.component.html, leaderboard/web/src/app/pages/teams/teams.component.spec.ts, leaderboard/web/src/app/pages/teams/teams.component.ts, leaderboard/web/src/app/pages/teams/teams.module.spec.ts, leaderboard/web/src/app/pages/teams/teams.module.ts
PTAL, don't delete the branch when PR approved.
=> Teams page scaffolding

leaderboard/web/src/app/pages/pages-menu.ts, leaderboard/web/src/app/pages/pages-routing.module.ts, leaderboard/web/src/app/pages/pages.module.ts, leaderboard/web/src/app/pages/teams/teams.component.html, leaderboard/web/src/app/pages/teams/teams.component.spec.ts, leaderboard/web/src/app/pages/teams/teams.component.ts, leaderboard/web/src/app/pages/teams/teams.module.spec.ts, leaderboard/web/src/app/pages/teams/teams.module.ts, provision-vm/azuredeploy.json
=> Leaderboard teams - Scaffolding for managing teams

provision-vm/azuredeploy.json
Fixes the issue caused by Azure account passwords with special characters.
=> Fix passing password with special characters

leaderboard/sentinel/helm/templates/deployment.yaml, leaderboard/sentinel/helm/values.yaml
- Adds the user-java API to be monitored by sentinel
=> add user-java api to sentinel

leaderboard/api/web/Models/Challenge.cs, leaderboard/api/web/Models/ChallengeDefinition.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix data context to allow null fields where appropriate

leaderboard/api/web/Models/Challenge.cs, leaderboard/api/web/Models/ChallengeDefinition.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix models

provision-vm/readme.md
Changed the deploy button to use master branch and not arm-clean-up
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fixed readme to use master

provision-proctor/setup.sh, provision-team/run_nginx.sh, provision-team/setup.sh
-  Fixes the proctor environment so it can succeed to be provisioned
- Fixes the setup usage to include new azure user/pass options
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> Fix proctor provisioning

provision-team/provision_sql_mobileapp.sh
Increase DTU to 200 in team deployment script.
=> Increase team SQL DTU to 200 (identical to proctor)

leaderboard/api/web/Controllers/SentinelController.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Change timeslice to nearest minute

provision-proctor/build_deploy_leaderboard_batch.sh
* fixes broken deployment for leaderboard batch deployment
=> fix leaderboard batch deployment

leaderboard/sentinel/main.go
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix http get method

leaderboard/sentinel/helm/templates/deployment.yaml, leaderboard/sentinel/helm/values.yaml, leaderboard/sentinel/main.go
- Fix the Sentinel Team Name and default query interval values
- Set the Sentinel Healthcheck to accept `*/*` and remove print log message to console
=> Tweak Sentinel

provision-proctor/setup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix broken proctor setup

provision-team/setup.sh
changed how the vars are passed to the service bus client
=> Changed passing parmaters to servicebus client

leaderboard/sentinel/main.go
I cleaned up the logging and also added a debugging flag to the env variables as the log messages are noisy.  This should make it pretty clean in normal mode.
=> Fix logging

leaderboard/sentinel/main.go
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> minor cleanup

provision-vm/proctorVMSetup.sh
Trying to remove the errors in the provisioning of the team env.
=> adding DEBIAN_FRONTEND=noninteractive

provision-vm/azuredeploy.json, provision-vm/labdeploy.json, provision-vm/proctorVMSetup.sh
Updates the custom script run by the extension and the ARM template to pass the parameters properly to the servicebus
=> Fix the custom script

provision-team/setup.sh
Removing the quotes in the message send to the attendees of the openhack.
* ...
```
[ ] Yes
[X] No
```
=> removed quotes for ipaddress in sbus message

leaderboard/sentinel/main.go
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix debug env variable default.

leaderboard/sentinel/main.go
Trying to fix the issue with traefik by adding timeout on http request and closing http connections.
@rguthriemsft please compile as I'm not sure about my env.
=> added closing httpclient and timeout on request

provision-proctor/configure_sql.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Initialize leaderboard Db

provision-proctor/provision_sql.sh, provision-team/provision_sql_mobileapp.sh
- Update team SQL DTU to 200 (S4)
- Update monitoring SQL DTU to 400 (S6)
=> Update SQL DB DTUs

simulator/DeviceSim/Controllers/ApiTripController.cs, simulator/DeviceSim/Program.cs
=> fixed HardAcceleration, TotalTrips and HardStops Arithmetic for UserProfile Update from POI

leaderboard/api/web/Controllers/LeaderboardController.cs, leaderboard/api/web/Data/LeaderboardContext.cs, leaderboard/api/web/Models/Challenge.cs, leaderboard/api/web/Models/ChallengeDefinition.cs, leaderboard/api/web/Models/Team.cs, leaderboard/api/web/Startup.cs, leaderboard/web/src/app/pages/challenges/challenges-add/challenges-add.component.html, leaderboard/web/src/app/pages/challenges/challenges-add/challenges-add.component.spec.ts, leaderboard/web/src/app/pages/challenges/challenges-add/challenges-add.component.ts, leaderboard/web/src/app/pages/challenges/challenges-delete/challenges-delete.component.html, leaderboard/web/src/app/pages/challenges/challenges-delete/challenges-delete.component.spec.ts, leaderboard/web/src/app/pages/challenges/challenges-delete/challenges-delete.component.ts, leaderboard/web/src/app/pages/challenges/challenges.component.html, leaderboard/web/src/app/pages/challenges/challenges.component.spec.ts, leaderboard/web/src/app/pages/challenges/challenges.component.ts, leaderboard/web/src/app/pages/challenges/challenges.module.spec.ts, leaderboard/web/src/app/pages/challenges/challenges.module.ts, leaderboard/web/src/app/pages/dashboard/servicestatus/servicestatus.component.ts, leaderboard/web/src/app/pages/pages-menu.ts, leaderboard/web/src/app/pages/pages-routing.module.ts, leaderboard/web/src/app/pages/pages.module.ts, leaderboard/web/src/app/pages/teams/teams-add/teams-add.component.html, leaderboard/web/src/app/shared/challenge.ts, leaderboard/web/src/app/shared/challengedefinition.ts
scaffold challenges and fix some API issues
=> Challenge scaffolding

provision-team/cleanup_environment.sh, provision-team/run_nginx.sh, provision-team/setup.sh
- Simplify scripts to run nginx
=> nginx team website fixes

provision-team/cleanup_environment.sh, provision-team/nginx/index.html, provision-team/setup.sh
- Fixes the kubeconfig not being copied
- Makes the zip file encrypted with a password
- Moves the kvstore dump file into the zip
- Fixes ownership of the `/home/azureuser` directory
- Sends zip password in the message to teams
=> Update / Fix zipped files for nginx

tripviewer/helm/templates/deployment.yaml, tripviewer/helm/values.yaml, tripviewer/web/Controllers/TripController.cs, tripviewer/web/Models/Stores/TripPointStore.cs, tripviewer/web/Models/Stores/TripStore.cs, tripviewer/web/Models/Stores/UserStore.cs, tripviewer/web/TripViewer.csproj, tripviewer/web/Utility/TripViewerConfiguration.cs, tripviewer/web/Views/Trip/Index.cshtml, tripviewer/web/Views/Trip/RenderMap.cshtml
Adding Map View  (Still Needs Ajax Auto-Refresh)
=> Adding Map View

provision-team/build_deploy_tripviewer.sh, provision-team/setup.sh, tripviewer/Dockerfile, tripviewer/helm/templates/deployment.yaml
- fix the helm chart spacing for ENV var
- Allow `BING_API_KEY` to be passed into helm chart
=> Update tripviewer helm chart

provision-proctor/InitLeaderboard.sql
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Finalize challenge names/points/descriptions

provision-team/configure_jenkins.sh
Added restart policy so Jenkins container will restart if the host VM is rebooted.
=> Add docker restart policy for Jenkins.

tools/get-teams.sh
This script will verify the deployment of each team environment and log failed ones for manual handling
* ...
```
[ ] Yes
[X] No
```
=> Added script to collect logs and credentials from the teams deployments.

provision-team/run_nginx.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update restart policy for nginx container

provision-proctor/Readme.md, provision-proctor/deploy_sentinel.sh, provision-proctor/setup.sh
Update the proctor environment deployment script and readme including forcing lowercase on the AAD name for helm.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
[X] Documentation content changes
```
=> Update how to deploy the monitoring environment

provision-team/jenkins/install_jenkins.sh
Add restart of Docker daemon on Jenkins and align helm client to 2.11.0. 
* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
Run helm init from a provisioned Jenkins VM.
To be tested with a full deployment after merge.
Verify that helm client is compatible with the AKS cluster
=> Updated helm version and restart docker daemon

tools/get-teams.sh
Add the ability to provide custom ssh key for deployment validation
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
=> Added ability to change ssh key

leaderboard/api/helm/values.yaml
Use uppercase char to match API calls from client
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix sentinel api ingress path

provision-team/jenkins/install_jenkins.sh
Adjust Helm to version 2.10.0
```
[ ] Yes
[X] No
```
=> Update helm 2.10.0

tools/get-teams.sh
Add a validation step for the presence of zip 
* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
=> Added validation if zip is present

provision-team/provision_sql.sh
scaling from 200 to 100 DTUs for SQL
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Change SQL DTU to 100 (S3)

provision-team/MYDrivingDB.sql
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fixing column widths and removing trigger

provision-proctor/Readme.md, provision-vm/readme.md
Found a few typos while reviewing 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
N/A
Wording and intent
N/A
=> Username was listed twice instead of Password.

provision-team/jenkins/azuredeploy.json, provision-team/jenkins/install_jenkins.sh
Add resiliency and speed on the Jenkins deployment script.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
=> Improvements on Jenkins deployment script

leaderboard/api/tests/IntegrationTests/IntegrationTests.csproj, leaderboard/api/web/Sentinel.csproj
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fixing security vulnerability

provision-proctor/deploy_ingress_dns.sh, tools/deploy-monitoring.sh, tools/get-teams.sh
Fixing the deployment of the monitoring environment
* ...
```
[X] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fixing monitoring script

provision-proctor/deploy_ingress_dns.sh
- Removes redundant (old) tiller check code
- Adds --debug --dry-run to the traefik install prior to the actual install for troubleshooting
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Minor tweak for helm install

provision-proctor/deploy_ingress_dns.sh, provision-team/deploy_ingress_dns.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fixed regex

provision-proctor/cleanup_monitor_environment.sh, provision-proctor/setup.sh
Fix the step to get the credentials
* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix cleanup environment

tools/deploy-sentinel.sh
Fix the path in the deployment sentinel
* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fixing sentinel script

tools/deploy-sentinel.sh
Fixing a typo in the sentinel deployment script.
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fixed typo

leaderboard/web/src/app/@theme/components/footer/footer.component.ts, leaderboard/web/src/app/@theme/components/header/header.component.html, leaderboard/web/src/app/pages/dashboard/dashboard.component.html, leaderboard/web/src/app/pages/dashboard/dashboard.component.ts, leaderboard/web/src/app/pages/pages-menu.ts
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Hide challenges/login and add team filter

leaderboard/web/src/app/pages/pages-menu.ts
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Change dashboard to api-status

provision-team/jenkins/install_jenkins.sh, provision-team/provision_aks.sh, provision-vm/proctorVMSetup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update to aks 1.11.5

provision-proctor/setup.sh, provision-team/setup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> add tenantId to kvstore

provision-vm/proctorVMSetup.sh
The apt-get upgrade on walinuxagent breaks the deployment script.
* ...
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Exclude walinuxagent from the apt-get upgrade

provision-team/provision_aks.sh
Fixing the AKS provisioning error
* ...
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fixed unbound variable error

tools/deploy-sentinel.sh
* ...Fixed a typo 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ... There is no change on code, so, no catastrophic events will come after this
There is no other information to share, up to now.
=> Minor fix on string #03

provision-vm/proctorVMSetup.sh
Making this change since the 2.1 version is reporting the following issue:
`The following packages have unmet dependencies: dotnet-sdk-2.1 : Depends: aspnetcore-runtime-2.1 (>= 2.1.8) but it is not going to be installed`
* ...
```
[X] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
Run a deployment
=> Upgrading to dotnet-sdk-2.2

provision-team/jenkins/install_jenkins.sh, provision-team/provision_aks.sh, provision-vm/proctorVMSetup.sh
Upgrade the version of AKS to 1.11.7 since 1.11.5 is not supported anymore.
* ...
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
=> Upgrade AKS to version 1.11.7

provision-vm/readme.md
Minor update to the SPN Name for internal deployments.
* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
=> Fixed SPN name for internal deployments

tools/validate-deployment.sh
Fix the if condition for exit code
=> check exit code

provision-team/cleanup_environment.sh, provision-team/run_nginx.sh, provision-vm/Docker/Dockerfile, provision-vm/Docker/startup.sh, provision-vm/azuredeploy.json, provision-vm/proctorVMSetup.sh
This collaboration work make us enable whole container deployment experience. 
We've done two things. 
1.  Enable nginx
2.  Move git clone from Container to Shell. It avoids caching issue of Docker.
=> fix: make sure a nginx container work propery

provision-vm/Docker/Dockerfile, provision-vm/Docker/Readme.md, provision-vm/Docker/startup.sh, provision-vm/azuredeploy.json, provision-vm/proctorVMSetup.sh
I make container log enabled to a file /home/azureuser/logs/teamdeploy.out
Once I success the whole deployment test, I'll share with you.
=> Adding logging feature to a file

provision-vm/azuredeploy.json
Hi @dcaro 
This PR for removing the dependency for developmentlog branch.
=> Remove the branch name

tools/validate-deployment.sh
- Change output log location
- fix filename for teamAAD
=> fix output log location

tools/validate-deployment.sh
Update log location to upload artifacts
Changed permissions on kubeconfig
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Modified artifacts location

provision-vm/Docker/Dockerfile
Add vim package for debugging.
=> add vim for debugging

tools/validate-deployment.sh
Ensure consistency and flexibility of names along the pipeline
* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update validation script to use Resource Group name as a variable 

provision-team/git_fetch.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix git fetch

provision-vm/proctorVMSetup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> uncomment docker run

monitoring/polling.ps1, monitoring/polling.sh
I wrote scripts both for PowerShell and Shell Script for monitoring one endpoint. 
```bash
$ ./polling.sh https://qiita.com/koara-local/items/04d3efd1031ea62d8db5
20190321-130653 | 200
20190321-130655 | 200
^C
$ ./polling.sh -i https://qiita.com/koara-local/items/04d3efd1031ea62d8db5
20190321-130700 | 200 | https://qiita.com/koara-local/items/04d3efd1031ea62d8db5
20190321-130702 | 200 | https://qiita.com/koara-local/items/04d3efd1031ea62d8db5
20190321-130704 | 200 | https://qiita.com/koara-local/items/04d3efd1031ea62d8db5
20190321-130705 | 200 | https://qiita.com/koara-local/items/04d3efd1031ea62d8db5
```
```powershell
PS > .\polling.ps1 -Uri https://github.com/Azure-Samples/openhack-devops-proctor -hasUri $true
21/03/2019 14:21:17 | 200 | …
```
=> Monitoring Scripts

tools/get-teams.sh
fixing the path in the validation script.
* ...
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fixed path after using a container

provision-vm/Docker/Readme.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update readme for docker container

provision-team/cleanup_environment.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix permissions on kubeconfig

resources/CHART-MANUAL.md
Added a manual how to use the chart used to deploy the API. 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
=> Added chart manual

provision-team/configure_sql.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Add FW rule for staging.

README.md
* Remove some broken links from the root README
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
*  Review the README file in the project root. Observe the removed links and updated formatting near the bottom. 
* Formatting of changed area in the README
=> remove dead links from root readme

resources/CHART-MANUAL.md
Adding --reuse-values to final code snippet in chart manual md file.
* ...
```
[ ] Yes
[ X] No
```
This adds a missing switch to the delete slot example.
=> adding --reuse-values to delete example.

provision-vm/azuredeploy.json, provision-vm/proctorVMSetup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Git branch shakeout

provision-team/setup.sh, provision-vm/Docker/startup.sh, provision-vm/azuredeploy.json, provision-vm/proctorVMSetup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Add switch to deploy from git branch

provision-team/configure_sql.sh, provision-team/jenkins/install_jenkins.sh, provision-team/provision_aks.sh, provision-vm/Docker/Dockerfile, provision-vm/Docker/Readme.md, provision-vm/proctorVMSetup.sh
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update to k8s 1.13, helm 2.14

provision-vm/Docker/Readme.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix docker cmd in readme.

provision-team/deploy_ingress_dns.sh
I ran a release against the changes and everything looks good.  Should fix FW error we were seeing.
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix ingress deploy via wait loop for Stage IP

provision-team/jenkins/install_jenkins.sh, provision-team/provision_aks.sh, provision-vm/Docker/Dockerfile
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Bump k8s, helm minor versions

provision-team/jenkins/install_jenkins.sh, provision-team/provision_aks.sh, provision-vm/Docker/Dockerfile
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Az to .71, k8s 1.13.9

provision-team/jenkins/install_jenkins.sh, provision-team/provision_aks.sh, provision-vm/Docker/Dockerfile
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> updating to 1.13.11 k8s

tripviewer/web/Views/Home/Index.cshtml
Disambiguate User and User Profile API references in the TripViewer
Remove Dotnet 2.1 references
Change Swagger endpoint from Trips Api 
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Refactoring (no functional changes, no api changes)
```
=> Openhack refresh tripviewer fix

tripviewer/web/Startup.cs
Insert missing HTTPClient Service
[ ] Yes
[x] No
```
[x] Bugfix
[ ] Feature
```
=> Add missing service for HTTPCient

provision-team/jenkins/install_jenkins.sh, provision-team/provision_aks.sh, provision-vm/Docker/Dockerfile
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update AKS to 1.15.10

provision-team/jenkins/install_jenkins.sh, provision-team/provision_aks.sh, provision-vm/Docker/Dockerfile
Tooling Updates:
kubectl /k8s from 1.15.10 to  1.17.11
helm from 2.14.3 to 2.17.0
azure cli 2.0.71 to 2.14.1
```
[ ] Yes
[x ] No
```
Maintenance Update
Replaces #337 whic did not have all the required kubectl updates
=> Maintenance/aks update to 1.17.11

provision-team/jenkins/Dockerfile
Fixing the working related to 2.237
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Moving from jenkins:2.237 to jenkins:2.268

provision-team/svcbusclient/Program.cs, provision-team/svcbusclient/svcbusclient.csproj
1. Update ServiceBus SDK from t1 to t2
2. Update files:
- ./provision-team/svcbusclient/Program.cs
- ./provision-team/svcbusclient/svcbusclient.csproj
@scottaddie, @AlexGhiondea, @lilyjma, @ramya-rao-a and @JoshLove-msft for notification.
=> Update ServiceBus SDK from t1 to t2
